### ISSUE TITLE
crash with Custom Npcs

### ISSUE THREAD

**Issue by MysticMoonPlays** [Mnesikos/SimplyCats#11]
when I try to make a Custom Npc using a simply cat it crashes my game. everytime I try and select the cat it crashes I can't tell if this is a compatibility thing or a bug I'll put the log at the bottom. the mods I have are
-Better animals plus 9.0.1
-biomes O plenty 7.0.1.2444
-chisels and bits 14.33
-controlling 3.0.6
-CTM 1.0.2.31
-custom npcs 05jul20
-dynamic surroundings 3.6.1.0
-dynamic surroundings huds 3.6.0.0
-dynamic trees 0.9.23
-dynamic trees bop 1.5.1
-mclib 2.2.2
-metamorph 1.2.6
-mysticallib 1.10.0
-mystical world 1.9.4
-optifine U F5
-orelib 3.6.0.1
-patchouli 23.6
-serene seasons 1.2.18
-vanilla fix 1.0.10- 150
-Xaeros Minimap 20.30.1
-simply cats(obviously) 0.0.3.1

-crash log-

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2021-04-10 20:14:07 EDT
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 1
    at com.github.mnesikos.simplycats.entity.core.Genetics$Eumelanin.getPhenotype(Genetics.java:194)
    at com.github.mnesikos.simplycats.entity.AbstractCat.getPhenotype(AbstractCat.java:398)
    at com.github.mnesikos.simplycats.entity.AbstractCat.setCatTexturePaths(AbstractCat.java:427)
    at com.github.mnesikos.simplycats.entity.AbstractCat.getCatTexture(AbstractCat.java:491)
    at com.github.mnesikos.simplycats.client.render.entity.RenderCat.getEntityTexture(RenderCat.java:40)
    at com.github.mnesikos.simplycats.client.render.entity.RenderCat.getEntityTexture(RenderCat.java:23)
    at net.minecraft.client.renderer.entity.NPCRendererHelper.getTexture(NPCRendererHelper.java:15)
    at noppes.npcs.client.gui.model.GuiCreationEntities.scrollClicked(GuiCreationEntities.java:110)
    at noppes.npcs.client.gui.util.GuiCustomScroll.mouseClicked(GuiCustomScroll.java:230)
    at noppes.npcs.client.gui.util.GuiNPCInterface.mouseClicked(GuiNPCInterface.java:149)
    at noppes.npcs.client.gui.model.GuiCreationScreenInterface.mouseClicked(GuiCreationScreenInterface.java:123)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: noppes.npcs.client.gui.model.GuiCreationEntities

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['MysticMoonPlays'/264, l='MpServer', x=-530.38, y=4.00, z=303.78]]
  Chunk stats: MultiplayerChunkCache: 168, 168
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-534,4,305), Chunk: (at 10,0,1 in -34,19; contains blocks -544,0,304 to -529,255,319), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
  Level time: 1922 game time, 1922 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 38 total; [EntityVillager['Villager'/320, l='MpServer', x=-463.12, y=5.00, z=346.52], EntityVillager['Villager'/322, l='MpServer', x=-474.93, y=5.00, z=376.64], EntityVillager['Villager'/323, l='MpServer', x=-451.73, y=4.94, z=352.77], EntityVillager['Villager'/324, l='MpServer', x=-455.14, y=4.94, z=353.01], EntitySlime['Slime'/261, l='MpServer', x=-540.03, y=4.00, z=325.58], EntityCustomNpc['Ahuatlea'/265, l='MpServer', x=-529.50, y=4.00, z=301.50], EntitySlime['Slime'/266, l='MpServer', x=-601.46, y=4.00, z=379.83], EntitySlime['Slime'/267, l='MpServer', x=-600.34, y=4.00, z=373.87], EntitySlime['Slime'/268, l='MpServer', x=-599.68, y=4.00, z=370.14], EntitySlime['Slime'/269, l='MpServer', x=-573.56, y=4.12, z=368.06], EntitySlime['Slime'/270, l='MpServer', x=-562.95, y=5.25, z=383.00], EntitySlime['Slime'/275, l='MpServer', x=-569.68, y=4.00, z=258.64], EntitySlime['Slime'/467, l='MpServer', x=-573.50, y=4.00, z=371.50], EntitySlime['Slime'/276, l='MpServer', x=-584.32, y=4.80, z=248.68], EntitySheep['Sheep'/277, l='MpServer', x=-608.50, y=4.00, z=281.50], EntitySlime['Slime'/278, l='MpServer', x=-557.26, y=4.00, z=337.71], EntityCow['Cow'/285, l='MpServer', x=-546.16, y=4.00, z=226.54], EntitySlime['Slime'/286, l='MpServer', x=-566.49, y=4.00, z=240.35], EntitySlime['Slime'/287, l='MpServer', x=-548.16, y=5.25, z=224.00], EntitySlime['Slime'/289, l='MpServer', x=-541.83, y=4.00, z=223.99], EntitySlime['Slime'/296, l='MpServer', x=-539.77, y=4.28, z=227.20], EntitySlime['Slime'/297, l='MpServer', x=-606.73, y=5.25, z=298.10], EntityVillager['Villager'/298, l='MpServer', x=-460.50, y=5.00, z=382.50], EntityPlayerSP['MysticMoonPlays'/264, l='MpServer', x=-530.38, y=4.00, z=303.78], EntitySlime['Slime'/304, l='MpServer', x=-474.70, y=4.00, z=242.87], EntitySlime['Slime'/305, l='MpServer', x=-484.76, y=4.42, z=262.53], EntitySlime['Slime'/503, l='MpServer', x=-567.50, y=4.00, z=371.50], EntitySlime['Slime'/312, l='MpServer', x=-463.96, y=4.42, z=314.97], EntitySlime['Slime'/504, l='MpServer', x=-534.37, y=4.00, z=226.13], EntitySlime['Slime'/313, l='MpServer', x=-487.55, y=4.00, z=367.43], EntitySlime['Slime'/314, l='MpServer', x=-490.67, y=5.14, z=357.78], EntitySlime['Slime'/506, l='MpServer', x=-477.80, y=4.00, z=228.67], EntityVillager['Villager'/315, l='MpServer', x=-463.92, y=4.00, z=340.47], EntityVillager['Villager'/316, l='MpServer', x=-466.59, y=3.94, z=365.44], EntitySlime['Slime'/508, l='MpServer', x=-580.91, y=4.42, z=253.77], EntityVillager['Villager'/317, l='MpServer', x=-453.52, y=5.00, z=337.72], EntityVillager['Villager'/318, l='MpServer', x=-451.52, y=5.00, z=341.70], EntityVillager['Villager'/319, l='MpServer', x=-452.15, y=4.94, z=349.96]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 822795832 bytes (784 MB) / 2017460224 bytes (1924 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 26 mods loaded, 25 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                | Version           | Source                                        | Signature                                |
       |:------ |:----------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft         | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp               | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJA | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | xaerominimap_core | 1.12.2-1.0        | minecraft.jar                                 | None                                     |
       | LCHIJA | biomesoplenty     | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
       | LCHIJA | chiselsandbits    | 14.33             | chiselsandbits-14.33 (1).jar                  | None                                     |
       | LCHIJA | controlling       | 3.0.6             | Controlling-3.0.6.jar                         | None                                     |
       | LCHIJA | ctm               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31 (2).jar                 | None                                     |
       | LCHIJA | customnpcs        | 1.12              | CustomNPCs_1.12.2-(05Jul20).jar               | None                                     |
       | LCHIJA | sereneseasons     | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar     | None                                     |
       | LCHIJA | orelib            | 3.6.0.1           | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround         | 3.6.1.0           | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dynamictrees      | 1.12.2-0.9.23     | DynamicTrees-1.12.2-0.9.23.jar                | None                                     |
       | LCHIJA | dynamictreesbop   | 1.12.2-1.5.1      | DynamicTreesBOP-1.12.2-1.5.1.jar              | None                                     |
       | LCHIJA | mclib             | 2.2.2             | mclib-2.2.2-1.12.2.jar                        | None                                     |
       | LCHIJA | metamorph         | 1.2.6             | metamorph-1.2.6-1.12.2.jar                    | None                                     |
       | LCHIJA | mysticalworld     | 1.12.2-1.9.4      | mysticalworld-1.12.2-1.9.4.jar                | None                                     |
       | LCHIJA | patchouli         | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
       | LCHIJA | simplycats        | 1.12.2-0.0.3.1    | simplycats-1.12.2-0.0.3.1.jar                 | None                                     |
       | LCHIJA | vanillafix        | 1.0.10-150        | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCHIJA | xaerominimap      | 20.30.1           | Xaeros_Minimap_20.30.1_Forge_1.12.jar         | None                                     |
       | LCHIJA | betteranimalsplus | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar            | None                                     |
       | LCHIJA | dshuds            | 3.6.0.0           | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | mysticallib       | 1.12.2-1.10.0     | mysticallib-1.12.2-1.10.0.jar                 | None                                     |
       | UD     | mclib_core        | 2.2.2             | minecraft.jar                                 | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      McLib core mod (mclib-2.2.2-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (2).jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_20.30.1_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13560 Compatibility Profile Context 26.20.11034.1006' Renderer: 'AMD Radeon(TM) Vega 6 Graphics'
  Patchouli open book context: n/a
  Suspected Mods: Simply Cats Mod (simplycats), CustomNPCs (customnpcs)
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: AMD Radeon(TM) Vega 6 Graphics GL version 4.6.13560 Compatibility Profile Context 26.20.11034.1006, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Warriors
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by MysticMoonPlays** [comment]
I hope I reported this right-

**Comment by Mnesikos** [comment]
Thank you for reporting this! I've know about it but never had an issue opened for it and forgot lol.

For future reference, in general it's nicer to upload the actual crash log file, or copy and paste it into a site like hastebin.com then share that link, but no big deal at all. Thank you again! I'll see if I can get this fixed soon.

**Comment by MysticMoonPlays** [comment]
oh ok sorry 
I'm new to reporting bugs and stuff

**Comment by MysticMoonPlays** [comment]
I am excited for this to be fixed cuz I want to do a warrior cats thing and I literally only made an account to report this one bug XD

**Comment by AstreAsteri** [comment]
Hi! I was wondering if this issue was ever resolved? Or is still on the list to be resolved?

**Comment by Mnesikos** [comment]
Still to be resolved; it's an incompatibility with how Simply Cats' textures work. I am working on a rewrite for the entirety of how SC's genetics (and thus textures) work, so that *might* fix things, but might not! We'll have to see.

**Comment by AstreAsteri** [comment]
Alrighty!! Take your time <3 I look foward to seeing how it goes!
